### ISSUE TITLE
Usability Enhancement: Improved clickable area

### ISSUE THREAD

**Issue by maedi** [Sebobo/jquery.smallipop#19]
Before:
![before](https://f.cloud.github.com/assets/601650/412373/193f07a6-abb0-11e2-9613-cbd506b196ef.png)
After:
![after](https://f.cloud.github.com/assets/601650/412374/1b594592-abb0-11e2-9260-0ba750021e77.png)

Smallipop should add the following to its styles to stop the divs which create the popup 'triangle' from preventing a user from clicking an element beneath.

``` css
.sipArrow,
.sipArrowBorder {
  pointer-events: none;
}
```
